insert into etat (libelle_etat) values 
	('sain'),
	('en soin'),
	('convalescent'),
	('maladie chronique'),
	('handicapé'),
	('contagieux');

insert into statut (libelle_statut) values
	('en soin'),
	('disponible'),
	('réservé'),
	('adopté'),
	('décédé');

insert into comportement (libelle_comportement) values
	('timide'),
	('peureux'),
	('agressif'),
	('sociable avec les adultes'),
	('Sociable avec les enfants'),
	('Sociable avec les chiens'),
	('Sociable avec les chats'),
	('Joueur'),
	('Calme'),
	('Destructeur'),
	('Propre'),
	('Non Propre');


insert into espece (libelle_espece)values
	('chien'),
	('chat');

insert into race (id_espece, libelle_race, taille_race) values
	(1,'Labrador Retriever','grand'),
	(1,'Berger Allemand','grand'),
	(1,'Golden Retriever','grand'),
	(1,'Bulldog Anglais','moyen'),
	(1,'Caniche','moyen'),
	(1,'Chihuahua','petit'),
	(1,'Beagle','moyen'),
	(1,'Rottweiler','grand'),
	(1,'Yorkshire Terrier','petit'),
	(1,'Boxer','grand'),
	(1,'Dachshund','petit'),
	(1,'Husky Sibérien','grand'),
	(1,'Border Collie','moyen'),
	(1,'Cocker Spaniel','moyen'),
	(1,'Dobermann','grand'),
	(1,'Shih Tzu','petit'),
	(1,'Akita Inu','grand'),
	(1,'Bichon Frisé','petit'),
	(1,'Malamute d''Alaska','grand'),
	(1,'Saint-Bernard','grand'),
	(1,'Dalmatien','grand'),
	(1,'Shar Pei','moyen'),
	(1,'Bull Terrier','moyen'),
	(1,'Épagneul Breton','moyen'),
	(1,'Jack Russell Terrier','petit'),
	(1,'Setter Irlandais','grand'),
	(1,'Chow Chow','grand'),
	(1,'Cane Corso','grand'),
	(1,'Staffordshire Bull Terrier','moyen'),
	(1,'American Staffordshire Terrier','moyen'),

	(2,'Abyssin','moyen'),
	(2,'American Bobtail','moyen'),
	(2,'American Curl','moyen'),
	(2,'American Shorthair','moyen'),
	(2,'American Wirehair','moyen'),
	(2,'Angora Turc','moyen'),
	(2,'Balinais','moyen'),
	(2,'Bengal','moyen'),
	(2,'Birman','moyen'),
	(2,'Bombay','moyen'),
	(2,'British Shorthair','moyen'),
	(2,'Burmese','moyen'),
	(2,'Chartreux','moyen'),
	(2,'Cornish Rex','moyen'),
	(2,'Devon Rex','petit'),
	(2,'Egyptian Mau','moyen'),
	(2,'European Shorthair','moyen'),
	(2,'Exotic Shorthair','moyen'),
	(2,'Havana Brown','moyen'),
	(2,'Highland Fold','moyen'),
	(2,'Himalayen','moyen'),
	(2,'Japanese Bobtail','moyen'),
	(2,'Korat','moyen'),
	(2,'Maine Coon','grand'),
	(2,'Manx','moyen'),
	(2,'Norvégien','grand'),
	(2,'Ocicat','grand'),
	(2,'Oriental','moyen'),
	(2,'Persan','moyen'),
	(2,'Peterbald','moyen'),
	(2,'Ragdoll','grand'),
	(2,'Russian Blue','moyen'),
	(2,'Sacré de Birmanie','moyen'),
	(2,'Savannah','grand'),
	(2,'Scottish Fold','moyen'),
	(2,'Selkirk Rex','moyen'),
	(2,'Siamois','moyen'),
	(2,'Sibérien','grand'),
	(2,'Singapura','petit'),
	(2,'Snowshoe','moyen'),
	(2,'Somali','moyen'),
	(2,'Sphynx','moyen'),
	(2,'Thai','moyen'),
	(2,'Tonkinois','moyen'),
	(2,'Turkish Van','grand');

insert into soin(libelle_soin,tarif_soin,frequence_soin) values
	('Stérilisation chat mâle', 90.00, null),
    	('Stérilisation chat femelle', 140.00, null),
    	('Vaccination', 35.00, null),
    	('Identification (puce ICAD)', 60.00, null),
    	('Vermifuge', 10.00, null),
    	('Antiparasitaire externe', 15.00, null),
    	('Consultation générale', 35.00, null),
    	('Soins dentaires', 120.00, null),
    	('Bilan sanguin', 70.00, null),
    	('Soins post-opératoires', 30.00, null),
    	('Traitement antibiotique', 25.00, null),
    	('Radiographie', 60.00, null),
   	('Bilan senior', 90.00, null),
    	('Soins dermatologiques', 45.00, null),
    	('Intervention chirurgicale (légère)', 180.00, null),
    	('Nettoyage des oreilles', 15.00, null),
    	('Coupe des griffes', 10.00, null),
    	('Test FIV / FeLV', 45.00, null),

    	('CHPPiL', 35.00, 1),
    	('Rage', 35.00, 3),
    	('Typhus (FPV)', 35.00, 1),
    	('Coryza', 35.00, 1),
    	('Leucose (FeLV)', 35.00, 2),
    	('Toux du chenil', 35.00, 1);

insert into employe(nom_employe, prenom_employe, login_employe, role_employe) values
	('Ardiet','Gabriel','ardietg','Responsable'),
	('Bujor','Gabriel','bujorg','Bénévole');
